import Head from "next/head";
import Navbar from "./Navbar";

function Layout({ children }) {
  return (
    <div className="overflow-x-hidden relative">
      <Head>
        <title>Archslate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="">
        <main>{children}</main>
      </div>
    </div>
  );
}

export default Layout;
