import Head from "next/head";
import Image from "next/image";
import googleLogo from "./assets/logo.png";
import adya from "./assets/adya.png";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-4 font-poppins ">
        <div className=" my-8 relative h-[100px] w-full">
          <Image
            src={googleLogo}
            fill
            className=" object-contain w-full"
            alt="banner"
          />
        </div>
        <h1 className="text-2xl text-gray-800 pb-4">
          Google's list of most beautiful women of 2022
        </h1>
        <div>
          <ul className="list-decimal pl-4 text-xl font-semibold">
            <li className="pb-2">Adya Anshy 😍 </li>
            <div className="pb-2 font-normal ">
              who cares about the rest 😌 ?But here goes cause... we are google
            </div>
            {/* <div className="pb-2 relative h-[600px] w-full">
              <Image
                src={adya}
                fill
                className=" object-cover w-full"
                alt="banner"
              />
            </div> */}
            <li className="pb-2">HoYeon Jung</li>
            <li className="pb-2">Zendaya</li>
            <li className="pb-2">Bella Hadid</li>
            <li className="pb-2">Beyonce</li>
          </ul>
        </div>

        <h1 className="text-2xl text-gray-800 pb-4">
          Google's list of most kindest women of 2022
        </h1>
        <div>
          <ul className="list-decimal pl-4 text-xl font-semibold">
            <li className="pb-2">Adya Anshy!! Ones again 🤩</li>

            {/* <div className="pb-2 relative h-[600px] w-full">
              <Image
                src={adya}
                fill
                className=" object-cover w-full"
                alt="banner"
              />
            </div> */}
            <li className="pb-2">HoYeon Jung</li>
            <li className="pb-2">Zendaya</li>
            <li className="pb-2">Bella Hadid</li>
            <li className="pb-2">Beyonce</li>
          </ul>
        </div>

        <h1 className="text-2xl text-gray-800 pb-4">
          Google's list of most coolest women of 2022
        </h1>
        <div>
          <ul className="list-decimal pl-4 text-xl font-semibold">
            <li className="pb-2">U know who it is 😌.... Adya Anshy!!!</li>

            {/* <div className="pb-2 relative h-[600px] w-full">
              <Image
                src={adya}
                fill
                className=" object-cover w-full"
                alt="banner"
              />
            </div> */}
            <li className="pb-2">HoYeon Jung</li>
            <li className="pb-2">Zendaya</li>
            <li className="pb-2">Bella Hadid</li>
            <li className="pb-2">Beyonce</li>
          </ul>
        </div>
        <p>
          We tried getting photos too of the winner here but could'nt find any
          suitable ones as winner is quite secretive as well.
        </p>
        <div className="pt-4 flex items-center">
          <div className="text-2xl">&copy;</div>

          <div className="relative h-[30px] w-[100px]">
            <Image
              className="object-contain"
              src={googleLogo}
              fill
              alt="banner"
            />
          </div>
        </div>
        <p>
          This is proprietary list of google. Made from general consensus.Thank
          You for visiting!!!😉
        </p>
      </main>
    </div>
  );
}
