import Head from "next/head";
import Link from "next/link";
import Navbar from "../components/Navbar";
import Tabs from "../components/Tabs";

export default function Home() {
  return (
    <div className=" bg-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Tabs></Tabs>
      </main>
    </div>
  );
}

export const ContentOne = () => {
  return (
    <div className="text-black">
      hello there
      <p>this is one</p>
    </div>
  );
};
